### ISSUE TITLE
Failed to create component for 'insert'

### ISSUE THREAD

**Issue by AntonioSun** [smicyk/groovy-jmeter#105]
I got `Failed to create component for 'insert'`. Here is the way to replicate the problem:

- Copy the [script.groovy](https://github.com/smicyk/groovy-jmeter/blob/develop/examples/structure/script.groovy) from `structure` to `structure-2` folder as-is.
- `structure-2` is parallel to `structure` folder
- `script.groovy` works in the `structure` folder just fine, but 
- For `script.groovy` under structure-2 to refer to structure, I made a simple change, to replace all `insert 'fragments/xxx'` as  `insert '../structure/fragments/xxx'`, but [groovy-jmeter](https://github.com/smicyk/groovy-jmeter) just cannot handle it any more:

```
Caught: java.lang.RuntimeException: Failed to create component for 'insert' reason: java.lang.NullPointerException: Cannot invoke method toURI() on null object
java.lang.RuntimeException: Failed to create component for 'insert' reason: java.lang.NullPointerException: Cannot invoke method toURI() on null object
        at script$_executeScript_closure1$_closure2.doCall(script.groovy:14)
        at script$_executeScript_closure1$_closure2.doCall(script.groovy)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at script$_executeScript_closure1.doCall(script.groovy:7)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at net.simonix.dsl.jmeter.TestScriptRunner.invokeBuilder(TestScriptRunner.groovy:175)
        at net.simonix.dsl.jmeter.TestScriptRunner$invokeBuilder$0.callStatic(Unknown Source)
        at net.simonix.dsl.jmeter.TestScriptRunner.configure(TestScriptRunner.groovy:154)
        at net.simonix.dsl.jmeter.TestScriptRunner$configure.call(Unknown Source)
        at net.simonix.dsl.jmeter.TestScriptBase.start(TestScriptBase.groovy:96)
        at net.simonix.dsl.jmeter.TestScriptBase$start$0.callCurrent(Unknown Source)
        at net.simonix.dsl.jmeter.TestScriptBase.start(TestScriptBase.groovy:42)
        at net.simonix.dsl.jmeter.TestScriptBase$start.callCurrent(Unknown Source)
        at script.executeScript(script.groovy:6)
        at net.simonix.dsl.jmeter.TestScript.run(TestScript.groovy:150)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
Caused by: java.lang.NullPointerException: Cannot invoke method toURI() on null object
        at net.simonix.dsl.jmeter.factory.AbstractTestElementFragmentFactory.newInstance(AbstractTestElementFragmentFactory.groovy:58)
        ... 22 more
```

**Comment by smicyk** [comment]
Hi, this is mostly because the main source for the insert is the script classpath which is folder where you execute the script. You can workaround it by adding structure folder to your class path e.g.:

```bash
groovy -cp ../structure script.groovy
```
Assuming the structure folder has fragments folder you don't need to change insert you can leave it as it was. Means the insert 'fragments/xxx'

**Comment by AntonioSun** [comment]
Thanks!
